### ISSUE TITLE
Apache NIFI as a PCF service

### ISSUE THREAD

**Issue by MohanBunny** [pivotal-cf/docs-spring-xd#1]
Hi,
I am just curious to know that is there any way to use Apache NIFI as service in Pivotal Cloud Foundry.
Because there is overlap with Spark XD and NiFi. Both do ingest (into a myriad of sinks). Both can do 'analysis'
So if it is possible to use NIFI as pivotal service,then how can we achieve it.What are the steps that we should follow.
Please give your valuable suggestions for the above.
Thank you,
Mohan.V

**Comment by bentarnoff** [comment]
See https://github.com/pivotal-cf/docs-pivotalcf-console/issues/5. Thanks.
